name: "Terraform CloudWatch Alarms"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches: ["main"]

jobs:
  terraform-cloudwatch-alarms:
    uses: ministryofjustice/operations-engineering/.github/workflows/reusable-workflow-terraform.yml@main
    with:
      workflow_name: "cloudwatch-alarms"
      path: "."
      terraform_version: "1.6.6"
      name: "CloudWatch Alarms"
    secrets:
      iam_role: ${{ secrets.AWS_DSD_CICD_ADMIN_ROLE_ARN }}
      repo_github_token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
